app = "issues-devin-backend"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[processes]
  app = "uvicorn main:app --host 0.0.0.0 --port 8000"
